CREATE SCHEMA LOJA_MESTRE_ANDRE;
USE LOJA_MESTRE_ANDRE;

create table clientes(
    nome varchar(100),
    senha varchar(20),
    cpf varchar(11) PRIMARY KEY,
    endereco varchar(200)
);

CREATE TABLE PRODUTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
DESCRICAO VARCHAR(100),
DESCONTO DECIMAL(10,2),
PRECO DECIMAL(10,2),
DATA_INICIO DATE);

CREATE TABLE FRETES(
ID INT PRIMARY KEY AUTO_INCREMENT,
CIDADE VARCHAR(100),
UF VARCHAR(2),
PRECO DECIMAL(10,2),
TEMPO INT
);

INSERT INTO FRETES(CIDADE, UF, PRECO, TEMPO) VALUES("BELO HORIZONTE", "MG", 10, 3);
INSERT INTO FRETES(CIDADE, UF, PRECO, TEMPO) VALUES("PORTO ALEGRE", "RS", 0, 1);

SELECT TEMPO FROM FRETES WHERE CIDADE = "BELO HORIZONTE" AND UF = "MG"